### ISSUE TITLE
Implement Transaction Fees

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#236]
### What 

Implement a simple first-party auction based on tx fees paid by users (that's the current model on BTC and ETH) but with a small burn. The model is identical with what XRP has been running for years. You can read more about it here https://xrpl.org/transaction-cost.html#server-state

See the original, internal issue: https://www.notion.so/monadic/Implement-Transaction-fees-46890453833b4a4bbc234055461029c6

### Requirements

1. Introduce an auction that is user-friendly and predictable from a user point of view. In economics, they call this 'dominant strategy incentive compatible'. In plain words, it translates to 'you always bid what you are truly willing to pay' and you are not trying to reason about what everyone else does

2. We want to create dynamics where the more transactions happening in the network the more our currency appreciates. Also to avoid congestion. that's why we are introducing token burns (a small amount from the fees is being burned) to reduce the overall supply and lead to price appreciation. our goal is to make our currency deflationary in the long run. I believe that most cryptocurrencies will introduce similar mechanisms in the future (Ethereum is doing it now, XRP has it for years)

I.e.:

- Allow the transaction authors to bid a "tip", used to prioritize the tx the chain takes on, especially in times of congestion.
- Provide a way for tx authors to get an estimate of how much they should bid to get their transactions validated and added to a block.
- Adjust the bid fee threshold based on the congestion of the network
- Charge the tx authors the total fee before running the transaction

### Roadmap

We should start with small steps and grow our way from there.

- [ ] Charge a fix hardcoded amount to the tx author for each transaction
    - [ ] Test that amount is withdrawn when the tx author has enough funds
    - [ ] Test that the tx is rejected when the tx author does not have enough funds
- [ ] Feature: Allow tx authors to include a fee bid in their tx
    - [ ] Add field to the tx
    - [ ] Define minimum fee bid?
    - [ ] Charge fee bid
- [ ] Feature: Define a complete fee setup
    - [ ] Define base_fee
    - [ ] Define `Weight` for each transaction
    - [ ] Calculate total_fee (`base_fee + len(tx) * length_fee + weightToFee(weight) + bid`. See more below [0])
- [ ] Make fee bid threeshold based on the congestion of the network
- [ ] Provide an api to get an estimate of how much an author should bid

#### [0] The anatomy of a total fee

The total fee that will be charged to the tx authors is composed of a few other fees.
      - `base_fee` will be a global fee charged to simply having submitted a tx. This fee serves the purpose of making the submission of transactions expensive enough to avoid users from flooding the system and causing a DOS or some other attack of that nature.
      - `length_fee` is a fee charged linearly accordingly to the chain storage space required by a transaction, in bytes. The more space a transaction needs, the bigger the fee in this respect will be. For instance, say we charge `RegisterProject` for the storage space taken by the `metadata` field. The more bytes it contains, the bigger the length fee.
      - `weight` is a number representing the complexity involved in processing a transaction. In other words, it represents the stress that processing that transaction causes the network. Say, the number of reads and writes, computed hashes, etc. We have to define these metrics better to come up with fair weights per transaction.
    -  `bid` fee  is essentially a tip, on top the other mandatory chore fees. When the network is under demand, miners need to make smart decisions as to which transactions to take on, like in a real market. The transaction with the best bids gets priority. So authors should adjust their bid to the urgency or necessity of having their transactions processed and added to the chain. 

#### Useful links

- [Adding fees to your substrate Runtime](https://www.shawntabrizi.com/substrate/adding-fees-to-your-substrate-runtime-module)
- https://haseebq.com/blockchain-fees-are-broken/
- https://hackingdistributed.com/2019/01/22/doing-fees-right/
- https://xrpl.org/transaction-cost.html#server-state

**Comment by geigerzaehler** [comment]
This looks like a very solid plan! Could you add a couple of more details on the base, length, and weight fees, though? I’d be interested in the rationale, resources, and especially how this plays together with the bid

**Comment by NunoAlexandre** [comment]
@geigerzaehler thanks for the feedback! I added a section explaining the different (sub) fees. Let me know if it helps!

**Comment by CodeSandwich** [comment]
Looks good, I agree that it's wiser to stand on the shoulders of the giant, which is Ripple.

Nitpicks:

1. We probably don't need a special tx field to make a bid, it can be calculated as `sum(inputs) - sum(outputs) - base_fee` - length_fee - weight.

1. Isn't `length_fee` part of the `weight` system?

**Comment by cloudhead** [comment]
> Looks good, I agree that it's wiser to stand on the shoulders of the giant, which is Ripple.
> 
> Nitpicks:
> 
> 1. We probably don't need a special tx field to make a bid, it can be calculated as `sum(inputs) - sum(outputs) - base_fee - length_fee - weight`.

+1, though I don't know what you mean by inputs/outputs, since we aren't using utxos. But conceptually you're right, we can just have a single `fee`, and substract all the fixed amounts. The remainder is the bid.

**Comment by NunoAlexandre** [comment]
@CodeSandwich

Regarding your first comment, we do need that bid field since that's at the core of the requirements.

Regarding the second point, there is some ambiguity between the two but they are not the same. `Weight` is more general. `length_fee` can be seen as `storage_fee`, which is quite specific.

**Comment by NunoAlexandre** [comment]
@cloudhead 

> +1, though I don't know what you mean by inputs/outputs, since we aren't using utxos. But conceptually you're right, we can just have a single fee, and substract all the fixed amounts. The remainder is the bid.

By input/outputs I think @CodeSandwich means reads/writes. Despite that detail, I am not sure if I agree or if I understand. I get from Ele that the goal really is to allow users to bid a certain amount that they willing to pay. How would that requirement be met if we don't allow the user to bid but only charge him based on the concrete costs associated with processing their transaction?

**Comment by cloudhead** [comment]
>  Make fee bid threshold based on the congestion of the network

I'm not sure what this means, but it doesn't sound like something we would want.

>  Define minimum fee bid?

This would be equivalent to a higher base_fee, so we don't need it.

**Comment by cloudhead** [comment]
> @cloudhead
> 
> > +1, though I don't know what you mean by inputs/outputs, since we aren't using utxos. But conceptually you're right, we can just have a single fee, and substract all the fixed amounts. The remainder is the bid.
> 
> By input/outputs I think @CodeSandwich means reads/writes. Despite that detail, I am not sure if I agree or if I understand. I get from Ele that the goal really is to allow users to bid a certain amount that they willing to pay. How would that requirement be met if we don't allow the user to bid but only charge him based on the concrete costs associated with processing their transaction?

The user knows all the fixed fees (their client should have that encodedd somewhere to know if they can afford the tx), so all they have to do is pay a little extra (the bid): `tx.fee = base_fee(tx) + tip`

**Comment by NunoAlexandre** [comment]
> I'm not sure what this means, but it doesn't sound like something we would want.

When blocks have a lot of space left, a low bid - in principle - will do. But when there's a lot of demand on the network, the minimum bid accepted will increase. That's what I mean on that part. 

> This would be equivalent to a higher base_fee, so we don't need it.

That's a good point, yeah.

**Comment by NunoAlexandre** [comment]
> The user knows all the fixed fees (their client should have that encodedd somewhere to know if they can afford the tx), so all they have to do is pay a little extra (the bid): tx.fee = base_fee(tx) + tip

AH! So the idea is to have a `fee` field, defined by the tx authors, that should basically include all the costs + tip and have that amount charged? I understood that the system would calculate transaction costs and, on top of that, would sum the `tip` defined by the author and charge that total amount in the end.

**Comment by CodeSandwich** [comment]
> > Make fee bid threshold based on the congestion of the network
> 
> I'm not sure what this means, but it doesn't sound like something we would want.

I understand this as a mechanism incentivizing users to spreading their transactions in time and avoid floods of transactions.

**Comment by cloudhead** [comment]
> I view this as a mechanism incentivizing users to spread their transactions in time and avoid floods of transactions.

I see, so the idea is to force a higher base fee when blocks are full? It seems like this is already covered by the basic bidding system, ie. if blocks are full, you will have to bid higher, therefore you may want (or have) to wait a little.

> AH! So the idea is to have a `fee` field, defined by the tx authors, that should basically include all the costs + tip and have that amount charged? I understood that the system would calculate transaction costs and, on top of that, would sum the `tip` defined by the author and charge that total amount in the end.

I think it's a good idea for the author to include the full amount he/she is willing to commit to paying, so that there are no surprises. If your client is out of date, and the fee is wrong, then the tx will fail. That's better than it succeeding, but charging you some arbitrary amount you haven't signed-off on.

With that in mind, you'd only need a single `fee` field, with the total. This is all just a suggestion though.

**Comment by NunoAlexandre** [comment]
Posting here some useful functions provided by substrate's `pallet-transaction-payment`.

Function that computes the total fee:

``` rust
/// Compute the final fee value for a particular transaction.
///
/// The final fee is composed of:
///   - _base_fee_: This is the minimum amount a user pays for a transaction.
///   - _len_fee_: This is the amount paid merely to pay for size of the transaction.
///   - _weight_fee_: This amount is computed based on the weight of the transaction. Unlike
///      size-fee, this is not input dependent and reflects the _complexity_ of the execution
///      and the time it consumes.
///   - _targeted_fee_adjustment_: This is a multiplier that can tune the final fee based on
///     the congestion of the network.
///   - (optional) _tip_: if included in the transaction, it will be added on top. Only signed
///      transactions can have a tip.
///
/// final_fee = base_fee + targeted_fee_adjustment(len_fee + weight_fee) + tip;
pub fn compute_fee(
```

A function that seems to provide a way of getting info over a fee associated to a tx:

``` rust
/// Query the data that we know about the fee of a given `call`.
///
/// As this module is not and cannot be aware of the internals of a signed extension, it only
/// interprets them as some encoded value and takes their length into account.
///
/// All dispatchables must be annotated with weight and will have some fee info. This function
/// always returns.
// NOTE: we can actually make it understand `ChargeTransactionPayment`, but would be some hassle
// for sure. We have to make it aware of the index of `ChargeTransactionPayment` in `Extra`.
// Alternatively, we could actually execute the tx's per-dispatch and record the balance of the
// sender before and after the pipeline.. but this is way too much hassle for a very very little
// potential gain in the future.
pub fn query_info<Extrinsic: GetDispatchInfo>(
	unchecked_extrinsic: Extrinsic,
	len: u32,
) -> RuntimeDispatchInfo<BalanceOf<T>>
```

--------

Currently, as discussed with Thomas yesterday, we already have `CargeTransactionPayment` in place at the client `transaction_extra_to_runtime_extra` function:

``` rust
let charge_transaction_payment = 
  pallet_transaction_payment::ChargeTransactionPayment::from(0);
```

So now we charge `0`. By adding that field that the tx authors specify, we can just use it here instead of `0` and it's all in I think.

**Comment by CodeSandwich** [comment]
> I see, so the idea is to force a higher base fee when blocks are full? It seems like this is already covered by the basic bidding system, ie. if blocks are full, you will have to bid higher, therefore you may want (or have) to wait a little.

It sometimes causes crisis, like unreasonably high fees and unstable fees. This is one of mitigations. Source: https://haseebq.com/blockchain-fees-are-broken/

**Comment by NunoAlexandre** [comment]
> I see, so the idea is to force a higher base fee when blocks are full? It seems like this is already covered by the basic bidding system, ie. if blocks are full, you will have to bid higher, therefore you may want (or have) to wait a little.

That's the idea, yes. I don't know if the substrate already offers this out of the box, note that I have that behaviour as a requirement to meet. If that's done automatically that's great!

> I think it's a good idea for the author to include the full amount he/she is willing to commit to paying, so that there are no surprises. If your client is out of date, and the fee is wrong, then the tx will fail. That's better than it succeeding, but charging you some arbitrary amount you haven't signed-off on.
>
> With that in mind, you'd only need a single fee field, with the total. This is all just a suggestion though.


That makes perfect sense. Looking at the `pallet_transaction_payment::ChargeTransactionPayment::from` function, that connects with the approach of having that single fee value that is all-inclusive.

**Comment by NunoAlexandre** [comment]
Done at 53c422609ff8c4a8bdb48623be1683021953f050.

It still misses burning a small percentage of the withdrawn amount and transfers the remainder to the block author, which we will do once we know how to obtain the block author.
