### ISSUE TITLE
Test first draft of “Getting Started” guide with users

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#329]
We want to test an early version of the getting started guide with three users. The following things are missing from the guide.

- [x] Links to the binaries (we can use the buildkite artifacts or Github releases) (#319)
- [ ]  Make devnet the default for binaries (#default #330)
- [x] Block mining log (#299)
- [x]  We developers need to be able to send them RAD (#331)

**Comment by CodeSandwich** [comment]
XLA's feedaback: https://www.notion.so/monadic/XLA-s-feedback-on-radicle-run-getting-started-guide-2a0ec0c7c9c24cd283aa567af7dad77f

**Comment by NunoAlexandre** [comment]
We've done this one :ok_man:
