### ISSUE TITLE
Updates to the Runtime

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#434]
Part of the [Registry Updates milestone](https://github.com/radicle-dev/radicle-registry/milestone/4)

#### Legend

🔨 - Issue
📝 - Something we will need to do or just keep in mind. Maybe pending becoming an issue.
📌 - A requirement or criteria

## Updates to the runtime

Independently on the type of update to the runtime, we need to:

- [x]  🔨 https://github.com/radicle-dev/radicle-registry/issues/437 Define a policy for developers on how to not break stuff when updating
- 📝 Publicly announced changelog
    Useful when some change might break previous user actions/patterns that worked previously.

- [x]  🔨 https://github.com/radicle-dev/radicle-registry/issues/438 Ensure that the dev node always runs the latest version

- 📝 Test run against the devnet, that should be always running at least the latest version of the ffnet
- [ ] 🔨 https://github.com/radicle-dev/radicle-registry/issues/444 Define release pipeline

### 1. Implementation changes

- [x]  🔨 https://github.com/radicle-dev/radicle-registry/issues/439 Need for criteria to verify that they are really just implementation changes
- 📌 The CLI must remain compatible
- Testing
    - [x]  🔨 https://github.com/radicle-dev/radicle-registry/issues/440  End to end tests need to run against both native and the wasm runtimes
- [x]  🔨https://github.com/radicle-dev/radicle-registry/issues/441  new miners and full nodes of the ffnet should run the latest native runtime version
    - 📌 substrate only runs native code if the execution strategy is set properly and if the version of the native code is compatible with the version of the on-chain runtime
- [x]  🔨 https://github.com/radicle-dev/radicle-registry/issues/442 existing miners and full nodes on the ffnet should run the latest wasm version
- [x]  🔨 https://github.com/radicle-dev/radicle-registry/issues/443 Build tool to submit WASM update transaction
   
### 2. Logic changes

- 📌 The CLI must remain compatible

### 3. State changes

- [ ]  🔨 https://github.com/radicle-dev/radicle-registry/issues/445 Devise way to make state changes backwards-compatible

**Comment by geigerzaehler** [comment]
We have tickets for all the tasks so I’m closing this.
