### ISSUE TITLE
Updates to the CLI

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#435]
Part of the [Registry Updates milestone](https://github.com/radicle-dev/radicle-registry/milestone/4)

#### Legend

🔨 - Issue
📝 - Something we will need to do or just keep in mind. Maybe pending becoming an issue.
📌 - A requirement or criteria

## Updates to the CLI

- [ ] 🔨 #26 Verify that the runtime version of the node we are connected to is supported
- 📌 Merge changes to master with companion docs update
    - 🔨 📝 Update docs disclaimer noting the version they cover
- 📝 Provide the new binary version through the releases page
- 📝 Announce new available version on discourse
- [ ]  🔨 #417 Announce new version available after running a command
- [x] 🔨 #427 Version the key-pairs.json file schema

**Comment by geigerzaehler** [comment]
Superseded by discussion in https://radicle.community/t/cli-runtime-compatibiliy/221/3
