### ISSUE TITLE
runtime: define a policy for developers for seamless integration when updating

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#437]
Part of https://github.com/radicle-dev/radicle-registry/issues/434

We need to define a policy we will follow whenever we need to update the runtime.

For instance, we know that:

- [x] we will need to bump the version of the runtime. (#454)
- [x] our storage deserialization must be backwards-compatible (#445)
- [x] a transaction containing the new WASM version will be broadcasted to the nodes (#443)

`To be completed`.

**Comment by geigerzaehler** [comment]
See [“Substrate Runtime Execution and Versions”](https://radicle.community/t/substrate-runtime- execution-and-versions/209) for more information on how the versioning works.

**Comment by geigerzaehler** [comment]
Closing this issue. The first item was solved and the remaining items are covered in the linked issues.
