### ISSUE TITLE
Current consensus implementation is not light client friendly

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#475]
Our implementation of the consensus is not light client friendly. To fully validate a block header a light client needs to be able to compute the target difficulty. The value of the target difficulty depends on the block timestamp which is only present in the block body or the chain state.

I’m not certain that we cannot work around this. However, to avoid surprises and keep the consensus close to proven algorithms we should put the block time stamp in the header.

This change would require either a fork of the block chain (i.e. the nodes need to be updated) or we need to reset the existing chains. The latter is less technical effort but requires coordination with existing participants. The former requires us to setup process, communication and infratstructure for the fork.

## Todo

- [ ] Decide on the strategy for releasing that change (fork or reset) and when we want to do it.
- [ ] Determine if there is an intermediate step that we can take that does not require a fork or reset.
- [ ] Validate that this works with a PoC PR

**Comment by burdges** [comment]
It's proof-of-work?  We've fancier block production schemes in substrate like BABE aka Ouroboros Praos that ostensibly make this problem equally hard by requiring a validator list, but maybe a validator list fits better with many people's threat model.  We've no great way to distribute validator list to light clients yet, but we're slowly working on that problem, and we're not doing research for proof-of-work.

**Comment by geigerzaehler** [comment]
Hey @burdges. Thanks for chiming in! Our consensus is indeed proof of work. One of the reasons why we chose PoW over what substrate champions is that it is more light client friendly. Of course you need to implement it properly ;). Fortunately this should be easy to accomplish.

While we’re using PoW now we’re also closely following the development on PoS and are excited about it’s possibilities. But the fact that it is still very much experimental and there are a couple unsolved problems along with governance concerns made us choose PoW. If you want to know more I’m sure @cloudhead is happy to provide more context.

**Comment by burdges** [comment]
Yes governance is hard.  We've many reasons for governance, but some relevant ones include parameter changes, which PoW encounters too, and slashing refunds, which PoS avoids by binding the blockhash into the production slot assignment.  

You can build PoS without slashing.  Academic PoS schemes like Ouroboros Praos mostly never slash, well true Praos ignores equivocations like PoW does.  We're not exploring that either, but actually we should do so for parachains, and maybe it's rather small code changes.  If you've slashing then you kinda want slashing refunds partially for your own bugs, but also for operators who do engage in high availability stupidity and equivocate or whatever. 

As for PoW, if one believes in VDFs then there are schemes like [Fantômette](https://arxiv.org/pdf/1805.06786.pdf) that bind slot assignment to the previous block hash, which provides almost exactly the same properties as true PoW.  We never explored Fantômette but yeah maybe we should do so for parachains.

**Comment by cloudhead** [comment]
I can't think of any way to make this work without the timestamp in the header, but should be an easy fix as you say. I'm curious what the validation rules are if any, for the timestamp, in the current implementation.

**Comment by burdges** [comment]
We approximate time in BABE using https://eprint.iacr.org/2019/942.pdf btw
