### ISSUE TITLE
Deploy upstream changes

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#480]
To merge the `upstream` branch into master and update the ffnet runtime with the changes we need to make at least the runtime changes to the state backwards compatible. (We may also want to release a client that is compatible with the new and the current version.)

The upstream branch includes two changes to the state schema. The field `state::Org::members` has been changed from `Vec<AccountId>` to `Vec<Id>`. Since we are not using a versioned schema for the `Org`s stored in the state yet we need to create a new storage for these orgs and forget about all the old organizations. The new orgs storage should use a versioned schema to be determined in https://github.com/radicle-dev/radicle-registry/issues/445.

The second change is in the type of the key for the projects store. It is changed from `(ProjectName, Id)` to `(ProjectName, ProjectDomain)`. This change requires us to abandon the old storage and use a new project storage.

The `upstream` branch also includes changes to the transaction types. These need to be accounted for if we want to release a version of the client and CLI that is compatible with both runtimes. Otherwise the client and CLI will only work with the version they were compiled with. I recommend to not tackle transaction compatibility so that we can merge and release the update sooner.

However, we definitely want to prevent CLI users from shooting themselves in the foot. Since we have dropped the `CheckVersion` we either need to add this again (#471) or have the CLI use the `onchain_runtime_version()` method to ensure compatibility.

The other semantic changes (like stricter validation for unregistering a user) are of no concern to the client, CLI, and the runtime.

### Plan

- [x] Merge `upstream` into `master`
- [x] Create policy for backwards compatible storage (https://github.com/radicle-dev/radicle-registry/issues/445)
- [x] Create PR that introduces new backwards compatible org storage for the `upstream` changes (#496)
- [x] Enforce strict CLI compatibility either with #471 or by using `onchain_runtime_version()`
- [x] Announce runtime upgrade on radicle.community mentioning that all orgs will be lost and that the CLI only works with one version (https://radicle.community/t/ffnet-chain-upgrade-v9/230)
- [x] Submit the new runtime to the ffnet.

**Comment by geigerzaehler** [comment]
What prevents us from merging `upstream` into master is that tools build from `master` will not work with the ffnet until we update the runtime. Specifically this prevents us from releasing new versions of the CLI and breaks the tools for external users building them from source. However, I believe that this is a risk we should take considering that maintaining to long-running branches creates a lot of overhead.

**Comment by NunoAlexandre** [comment]
It all looks sound to me, we just miss to have an action point to also be backwards compatible in regard with the changes to the `Projects` storage, where its id type was `(ProjectName, Id)` and has become (#477) `(ProjectName, ProjectDomain)`.

**Comment by CodeSandwich** [comment]
Sound good!

**Comment by geigerzaehler** [comment]
@CodeSandwich and I discussed if releasing client and CLI that are compatible with the new and the old runtime version should be included here. We came to the conclusion that this would require a lot of effort and unnecessarily delay this ticket. We will not create a backwards compatible client and CLI as part of this.

**Comment by geigerzaehler** [comment]
Runtime upgrade was [announced](https://radicle.community/t/ffnet-chain-upgrade-v9/230)

**Comment by geigerzaehler** [comment]
New runtime has been deployed to the ffnet

**Comment by NunoAlexandre** [comment]
> New runtime has been deployed to the ffnet

`spec_version: 9`?

**Comment by geigerzaehler** [comment]
> > New runtime has been deployed to the ffnet
> 
> `spec_version: 9`?

Yes
